package com.rainier.model;

import java.io.Serializable;

public class RoleModule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemodule.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemodule.RoleID
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemodule.ModuleID
     *
     * @mbggenerated
     */
    private Integer moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rolemodule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemodule.ID
     *
     * @return the value of rolemodule.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemodule.ID
     *
     * @param id the value for rolemodule.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemodule.RoleID
     *
     * @return the value of rolemodule.RoleID
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemodule.RoleID
     *
     * @param roleid the value for rolemodule.RoleID
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemodule.ModuleID
     *
     * @return the value of rolemodule.ModuleID
     *
     * @mbggenerated
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemodule.ModuleID
     *
     * @param moduleid the value for rolemodule.ModuleID
     *
     * @mbggenerated
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }
}